apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1m
  targetNamespace: kube-system
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 1m
      version: 1.14.5
  values:
    cluster:
      name: smig-mgmt
      id: 11
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: false
        labels:
          release: prometheus-stack
    dashboards:
      enabled: true
    hubble:
      metrics:
        enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - icmp
        - http
        dashboards:
          enabled: true
        serviceMonitor:
          enabled: false
          namespace: monitoring
          labels:
            release: prometheus-stack
      relay:
        enabled: true
        prometheus:
          enabled: true
          serviceMonitor:
            enabled: false
            namespace: monitoring
            labels:
              release: prometheus-stack
      ui:
        enabled: true
        baseUrl: "/"
    version: 1.14.5
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: false
          namespace: monitoring
          labels:
            release: prometheus-stack
      dashboards:
        enabled: true
    envoy:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: false
          namespace: monitoring
          labels:
            release: prometheus-stack
    clustermesh:
      apiserver:
        metrics:
          enabled: false
          serviceMonitor:
            enabled: false
            namespace: monitoring
            labels:
              release: prometheus-stack