# Application to point to charts/alloy
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: 'https://github.com:gaianetes/kubula.git'
    targetRevision: feature/update-install-script
    path: apps/monitoring/alloy
    helm:
      releaseName: alloy
      values: |-
        alloy:
          clustering:
            enabled: true
          mounts:
            varlog: true
            dockercontainers: true
          configMap:
            create: true
      # valueFiles:
      # - "alloy.values.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true