alloy:
  clustering:
    enabled: true
  mounts:
    varlog: true
    dockercontainers: true
  configMap:
    create: true
ingress:
  enabled: false
  ingressClassName: cilium
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  path: /
  hosts:
    - alloy.smigula.io
  tls:
  - secretName: alloy-tls-secret
    hosts:
      - alloy.smigula.io