grafana:
  grafana.ini:
    server:
      domain: grafana.smigula.io
  namespaceOverride: "monitoring"
  adminPassword: "fe31676d30b70ccb286ba8cd"
  serviceMonitor:
    enabled: true 
    namespace: "monitoring"
  networkPolicy:
    enabled: false
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: '1'
      memory: 2Gi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
      - name: Mimir
        uid: mimir
        type: prometheus
        url: http://{{ .Release.Name }}-mimir-nginx/prometheus
        isDefault: true
        editable: true
        orgId: 1
        jsonData:
          httpHeaderName1: X-Scope-OrgID
      - name: Loki
        uid: loki
        type: loki
        url: http://{{ .Release.Name }}-loki-gateway
        isDefault: false
        orgId: 1
        jsonData:
          httpHeaderName1: X-Scope-OrgID
      - name: Tempo
        uid: tempo
        type: tempo
        url: http://{{ .Release.Name }}-tempo-query-frontend:3100
        isDefault: false
        jsonData:
          httpHeaderName1: X-Scope-OrgID
          tracesToLogsV2:
            datasourceUid: loki
          lokiSearch:
            datasourceUid: loki
          tracesToMetrics:
            datasourceUid: mimir
          serviceMap:
            datasourceUid: mimir
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      prometheusViewsNodes:
        gnetId: 15759
        revision: 28
        datasource: Prometheus
  ingress:
    enabled: false
    ingressClassName: cilium
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    path: /
    hosts:
      - grafana.smigula.io
    tls:
    - secretName: grafana-tls-secret
      hosts:
        - grafana.smigula.io
  persistence:
    enabled: true
    size: 50Gi
    storageClassName: nfs-client