# Application to point to charts/alloy
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-distributed
  namespace: argocd
spec:
  project: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.79.1
    chart: loki-distributed
    helm:
      releaseName: loki
      values: |-
        global:
          dnsService: "rke2-coredns-rke2-coredns"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true