---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: web
    advertise: "cilium"
  name: web
spec:
  containers:
  - image: nginx
    name: web
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    advertise: "cilium"
  # annotations:
  #   io.cilium/lb-ipam-ips: 192.168.1.41
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: web
  externalTrafficPolicy: Local
  type: LoadBalancer