{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: arcadedb-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  rootPassword: {{ .Values.secret.password | b64enc | quote }}
{{- end }}