apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  chart: https://github.com/cilium/charts/blob/master/cilium-1.15.5.tgz
  # chart: cilium/cilium
  # repo: https://helm.cilium.io/
  # version: 1.15.5
  valuesContent: |-
    cluster:
      name: smig-cluster1
      id: 11
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: false
    dashboards:
      enabled: true
    hubble:
      metrics:
        enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - icmp
        - http
        dashboards:
          enabled: true
      relay:
        enabled: true
        prometheus:
          enabled: true
      ui:
        enabled: true
        baseUrl: "/"
    version: 1.15.5
    operator:
      prometheus:
        enabled: true
      dashboards:
        enabled: true