---
- name: Colorize root shell prompt
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: 'export PS1="\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"' # noqa: yaml[line-length]
    state: present
- name: Alias vi to vim
  ansible.builtin.lineinfile:
    path: /root/.bashrc
    line: "alias vi='vim'"
    state: present
- name: Create vim configuration file
  ansible.builtin.file:
    path: /root/.vimrc
    state: touch
    owner: root
    group: root
    mode: "0644"
- name: Configure vim
  ansible.builtin.blockinfile:
    path: /root/.vimrc
    block: |
      set nocompatible
      set number
      set autoindent
      syntax on
      highlight Comment ctermfg=LightCyan
    marker: ""
    state: present
- name: Disable GSSAPIAuthentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^GSSAPIAuthentication"
    line: "GSSAPIAuthentication no"
    state: present
- name: Update CA bundle (Rocky)
  ansible.builtin.get_url:
    url: https://curl.haxx.se/ca/cacert.pem
    dest: /etc/pki/tls/certs/ca-bundle.crt
    force: true
    mode: "0644"
  when: ansible_distribution == "Rocky"
- name: Install epel repo (Rocky)
  ansible.builtin.dnf:
    name: "epel-release"
    state: latest
  when: ansible_distribution == "Rocky"
- name: Upgrade all packages (Rocky)
  ansible.builtin.dnf:
    name: "*"
    state: latest
  when: ansible_distribution == "Rocky"
- name: Install packages (Rocky)
  ansible.builtin.dnf:
    name: "{{ init_packages }}"
    state: latest
  when: ansible_distribution == "Rocky"
- name: Autoremove DNF packages
  ansible.builtin.dnf:
    autoremove: true
- name: Create rke2 user
  ansible.builtin.user:
    name: "{{ init_user_name }}"
    uid: 1001
    shell: /bin/bash
    groups: wheel
    append: true
    create_home: true
    password: "{{ init_user_password }}"
