
- name: Colorize root shell prompt
  lineinfile:
    path: /root/.bashrc
    line: 'export PS1="\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h:\[$(tput sgr0)\]\[\033[38;5;6m\][\w]:\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"'
    state: present

- name: Alias vi to vim
  lineinfile:
    path: /root/.bashrc
    line: "alias vi='vim'"
    state: present

- name: Create vim configuration file
  file:
    path: /root/.vimrc
    state: touch
    owner: root
    group: root
    mode: 0644

- name: Configure vim
  blockinfile:
    path: /root/.vimrc
    block: |
      set nocompatible
      set number
      set autoindent
      syntax on
      highlight Comment ctermfg=LightCyan
    marker: ""
    state: present

- name: Disable GSSAPIAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^GSSAPIAuthentication"
    line: "GSSAPIAuthentication no"
    state: present

- name: Update CA bundle (Rocky)
  get_url:
    url: https://curl.haxx.se/ca/cacert.pem
    dest: /etc/pki/tls/certs/ca-bundle.crt
    force: yes
  when: ansible_distribution == "Rocky"

- name: Install epel repo (Rocky)
  dnf:
    name: "epel-release"
    state: latest
  when: ansible_distribution == "Rocky"

- name: Upgrade all packages (Rocky)
  dnf:
    name: "*"
    state: latest
  when: ansible_distribution == "Rocky"

- name: Install packages (Rocky)
  dnf:
    name: 
    - bash-completion
    - curl
    - git
    - rsync
    - screen
    - tcpdump
    - vim
    - wget
    - nano
    - tmux 
    - jq
    - vim-common
    - iscsi-initiator-utils
    - unzip
    - tar
    - nfs-utils
    state: latest      
  when: ansible_distribution == "Rocky"

- name: Autoremove DNF packages
  dnf:
    autoremove: true

- name: Clean up
  shell: dnf clean all