apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: argo-cd
  namespace: flux-system
spec:
    interval: 1m
    url: https://argoproj.github.io/argo-helm
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 1m
  targetNamespace: argocd
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argo-cd
        namespace: flux-system
      interval: 1m
      version: 5.51.0
  values:
    params:
      server.insecure: true
    controller:
      metrics:
        serviceMonitor:
          enabled: true
          namespace: monitoring
    redis:
      metrics:
        serviceMonitor:
          enabled: true
          namespace: monitoring
    server:
      metrics:
        serviceMonitor:
          enabled: true
          namespace: monitoring
    repoServer:
      metrics:
        serviceMonitor:
          enabled: true
          namespace: monitoring
    applicationSet:
      metrics:
        serviceMonitor:
          enabled: true
          namespace: monitoring
    rbac:
      defaultPolicy: 'role:readonly'
      policy: |
        g, argocd-admin, role:admin
        g, argocd-manager, role:admin
        g, argocd-server, role:admin
        g, argocd-server, role:readonly
        g, argocd-server, role:repo-server
        g, argocd-server, role:server
        g, argocd-server, role:users
        g, argocd-server, role:viewer
        g, argocd-server, role:writer
        g, argocd-server, scope:*, apiGroups:*
        g, system:authenticated, role:admin
        g, system:authenticated, role:readonly
        g, system:authenticated, role:repo-server
        g, system:authenticated, role:server
        g, system:authenticated, role:users
        g, system:authenticated, role:viewer
        g, system:authenticated, role:writer
        g, system:authenticated, scope:*, apiGroups:*
        g, system:serviceaccounts, role:admin
        g, system:serviceaccounts, role:readonly
        g, system:serviceaccounts, role:repo-server
        g, system:serviceaccounts, role:server
        g, system:serviceaccounts, role:users
        g, system:serviceaccounts, role:viewer
        g, system:serviceaccounts, role:writer
        g, system:serviceaccounts, scope:*, apiGroups:*
        g, system:unauthenticated, role:admin
        g, system:unauthenticated, role:readonly
        g, system:unauthenticated, role:repo-server
        g, system:unauthenticated, role:server