---
- name: Import elrepo repo key
  ansible.builtin.rpm_key:
    key: "{{ kernel_elrepo_repo_gpg_key_url }}"
    state: present
- name: Install elrepo repo
  ansible.builtin.dnf:
    name: "{{ kernel_elrepo_repo_url }}"
    state: present
- name: Install kernel packages
  ansible.builtin.dnf:
    name: "{{ kernel_elrepo_packages }}"
    state: latest
    enablerepo: elrepo-kernel
  become: true
- name: Disable selinux
  ansible.posix.selinux:
    state: "{{ kernel_enable_selinux_mode }}"
  become: true
