- name: 1. import elrepo repo key
  rpm_key:
    key:  https://www.elrepo.org/RPM-GPG-KEY-elrepo.org
    state: present
- name: 2. install elrepo repo
  ansible.builtin.dnf:
    name:  https://www.elrepo.org/elrepo-release-8.el8.elrepo.noarch.rpm
    state: present 

- name: Install kernel packages
  ansible.builtin.dnf:
    name: 
      - kernel-ml 
      - kernel-ml-core 
      - kernel-ml-headers 
      - kernel-ml-modules 
      - kernel-ml-modules-extra
    state: latest
    enablerepo: elrepo-kernel
  become: true

- name: Disable selinux
  ansible.posix.selinux:
    state: disabled
  become: true