---

- name: Install kernel packages
  dnf:
    name: 
      - kernel-ml 
      - kernel-ml-core 
      - kernel-ml-headers 
      - kernel-ml-modules 
      - kernel-ml-modules-extra
    state: latest
    enablerepo: elrepo-kernel
  become: true

- name: Disable selinux
  selinux:
    state: disabled
  become: true