server:
  count: 1
  memory: 2048
  cpus: 2
workers:
  count: 1
  memory: 4192
  cpus: 4
rke2:
  version: v1.30.0+rke2r1
  channel: latest
  token: e2f8e040d9701df33d5dca8dacf8012d
vagrant:
  min_version: 2.2.17
  box: generic/rocky8
  cpus: 2
  memory: 4192
network:
  type: private_network
  private_nic_type: 82545EM
  netmask: 255.255.255.0
  base_ip: 10.42.0
  cni: calico
k9s:
  version: v0.32.4
  install: true
helm:
  install: true
  version: v3.15.1