ENV['VAGRANT_I_KNOW_WHAT_IM_DOING_PLEASE_BE_QUIET'] = 'true'
ENV['VAGRANT_NO_PARALLEL'] = 'no'

Vagrant.require_version ">= 2.2.17"

Vagrant.configure("2") do |config|
  # For user example 
  # config.vagrant.plugins = ["vagrant-reload", "vagrant-rke2"]
  # For dev work
  config.vagrant.plugins = ["vagrant-reload"]

  config.vm.provider "libvirt" do |v|
    v.cpus = 2         
    v.memory = 4096
  end

  config.vm.provider "virtualbox" do |v|
    v.cpus = 2         
    v.memory = 4096
    v.linked_clone = true
  end

  server_ip = "10.10.10.100"
  worker_base_ip = "10.10.10"
  # define number of workers
  workers = 3
  # define number of servers
  # if we want to make this a HA cluster, we can set this to 3 and use something like HAProxy
  servers = 1

  config.vm.define "server" do |server|
    server.vm.box = 'generic/rocky8'
    server.vm.hostname = 'server'
    server.vm.network "private_network", ip: server_ip, netmask: "255.255.255.0"
    # generic/ubuntu2004 suffers from poor default dns servers, creates problems with hitting github.com immediately
    # server.vm.provision "Set DNS", type: "shell", inline: "systemd-resolve --set-dns=8.8.8.8 --interface=eth0"
    server.vm.provision "Create Server Manifests Directory", type: "shell", inline: "sudo mkdir -p /var/lib/rancher/rke2/server/manifests"
    # echo out the current user
    server.vm.provision "Echo Current User", type: "shell", inline: "echo $USER"
    # upload file
    server.vm.provision "Upload Cilium Config", type: "file", source: "./files/rke2-cilium-helm-config.yaml", destination: "/tmp/rke2-cilium-helm-config.yaml"
    # copy file to /var/lib/rancher/rke2/server/manifests/rke2-cilium-helm-config.yaml
    # server.vm.provision "Copy Cilium Config", type: "shell", inline: "sudo cp /tmp/rke2-cilium-helm-config.yaml /var/lib/rancher/rke2/server/manifests/rke2-cilium-helm-config.yaml"
    server.vm.provision :rke2, run: "once" do |rke2|
      rke2.env = %w[INSTALL_RKE2_CHANNEL=latest INSTALL_RKE2_TYPE=server INSTALL_RKE2_VERSION=v1.30.0+rke2r1]
      rke2.config_mode = '0644' # side-step https://github.com/k3s-io/k3s/issues/4321
       # note that write-kubeconfig-mode needs to be a string
      rke2.config = <<~YAML
        write-kubeconfig-mode: '0644'
        node-external-ip: #{server_ip}
        node-ip: #{server_ip}

        token: vagrant-rke2
        cni: calico
        # disable:
        # - rke2-canal
        # - rke2-kube-proxy
        # network:
        #     plugin: none
        # cluster-cidr: 10.42.0.0/16
        # service-cidr: 10.96.0.0/16
      YAML
    end
  end

  # iterate over the number of workers
  workers.times do |i|
    config.vm.define "worker-#{i+1}" do |worker|
        worker.vm.box = 'generic/rocky8'
        worker.vm.hostname = "worker-#{i+1}"
        worker.vm.network "private_network", ip: "#{worker_base_ip}.#{i+103}", netmask: "255.255.255.0"
        # worker.vm.provision "Set DNS", type: "shell", inline: "systemd-resolve --set-dns=
        worker.vm.provision :rke2, run: "once" do |rke2|
            rke2.env = %w[INSTALL_RKE2_CHANNEL=latest INSTALL_RKE2_TYPE=agent INSTALL_RKE2_VERSION=v1.30.0+rke2r1] 
            rke2.config_mode = '0644' # side-step
            rke2.config = <<~YAML
                write-kubeconfig-mode: 0644
                node-external-ip: #{worker_base_ip}.#{i+103}
                node-ip: #{worker_base_ip}.#{i+103}
                
                server: https://#{server_ip}:9345
                token: vagrant-rke2
            YAML
        end
    end
  end
end