---
# server or agent?
rke2_role: server
rke2_version: v1.30.3+rke2r1
rke2_images_url: https://github.com/rancher/rke2/releases/download/v1.30.3%2Brke2r1/rke2.linux-amd64.tar.gz
rke2_artifacts_path: "/vagrant/dist/artifacts/"
rke2_download_images: true
rke2_cluster_name: cluster2
rke2_prometheus_enabled: true
rke2_prometheus_service_monitor_enabled: false
rke2_dashboards_enabled: true
rke2_hubble_metrics_dashboards_enabled: true
rke2_hubble_metrics_service_monitor_enabled: true
rke2_service_monitor_namespace: monitoring
rke2_hubble_relay_enabled: true
rke2_hubble_relay_prometheus_enabled: true
rke2_hubble_relay_prometheus_service_monitor_enabled: true
rke2_hubble_ui_enabled: true
rke2_hubble_ui_base_url: "/"
rke2_cilium_version: 1.16.1
rke2_operator_prometheus_enabled: true
rke2_operator_prometheus_service_monitor_enabled: true
rke2_operator_dashboards_enabled: true
rke2_envoy_prometheus_enabled: false
rke2_envoy_prometheus_service_monitor_enabled: false
rke2_clustermesh_apiserver_metrics_enabled: true
rke2_clustermesh_apiserver_metrics_service_monitor_enabled: true
rke2_l2announcements_enabled: true
rke2_kube_proxy_replacement: true
rke2_external_ips_enabled: true
rke2_ipam_mode: kubernetes
rke2_socket_lb_host_namespace_only: true
rke2_bgp_control_plane_enabled: true
rke2_hubble_enabled: true
rke2_cluster_id: 01