---

- name: Setting up the infrastructure
  become: true
  hosts: localhost
  gather_facts: yes
  roles:
    - role: init
    - role: kernel
    - role: network
    - role: storage
    - role: cilium
    - role: rke2
  vars:
    rke2_role: server
    master_ip: "192.168.1.200"
    cilium_cli_version: "v0.16.3"
    static_ip: "192.168.1.200"
    static_prefix: "22"
    static_gateway: "192.168.1.1"
    gateway_ip: "192.168.1.1"
    static_dns1: "192.168.1.6"
    static_dns2: "8.8.8.8"
