---

- name: Setting up the infrastructure
  become: true
  roles:
    - setup
    - kernel
    - networking
    - storage
    - cilium
    - rke2
  vars:
    rke2_role: server
    master_ip: "192.168.1.200"
    cilium_cli_version: "v0.16.3"
    static_ip: "192.168.1.200"
    gateway_ip: "192.168.1.1"
    static_dns1: "192.168.1.6"
    static_dns2: "8.8.8.8"