---

- name: Install the Cilium CLI
  block:
  - name: Download the Cilium CLI
    get_url:
      url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_cli_version }}/cilium-linux-amd64.tar.gz"
      dest: "/tmp/cilium-linux-amd64.tar.gz"
      mode: 0644
  - name: Extract the Cilium CLI
    unarchive:
      src: "/tmp/cilium-linux-amd64.tar.gz"
      dest: "/usr/local/bin"
      remote_src: yes
      extra_opts: [--strip-components=1]