- name: Ensure tmp directory exist
  file:
    path: "{{playbook_dir}}/files/tmp"
    state: directory

- name: Install Cilium CLI
  include_tasks: cli.yaml
  when: cilium_install

# include tasks from config
- name: Configure Cilium
  include_tasks: config.yaml
  when: cilium_install and cilium_master

